import docxLogo from "../../assets/fileExt/docx-icon.png";
import pdfLogo from "../../assets/fileExt/pdf-icon.png";
import jpgLogo from "../../assets/fileExt/jpg-icon.png";
import dwgLogo from "../../assets/fileExt/dwg-icon.png";
import pngLogo from "../../assets/fileExt/png-icon.png";

const projectFiles = [
  {
    id: 1,
    fileTitle: "A Blok Mimari Plan",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: dwgLogo,
    extension: "dwg",
    isUptoDate: true,
    modificationDate: "20.10.2021",
  },
  {
    id: 2,
    fileTitle: "B Blok Mimari Plan",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: dwgLogo,
    extension: "dwg",
    isUptoDate: true,
    modificationDate: "12.10.2021",
  },
  {
    id: 3,
    fileTitle: "C Blok Mimari Plan",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: dwgLogo,
    extension: "dwg",
    isUptoDate: false,
    modificationDate: "15.11.2021",
  },
  {
    id: 4,
    fileTitle: "D Blok Mimari Plan",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: dwgLogo,
    extension: "dwg",
    isUptoDate: true,
    modificationDate: "05.08.2021",
  },
  {
    id: 5,
    fileTitle: "E Blok Mimari Plan",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: dwgLogo,
    extension: "dwg",
    isUptoDate: false,
    modificationDate: "08.11.2021",
  },
  {
    id: 6,
    fileTitle: "A Blok Fotoğrafı",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: jpgLogo,
    extension: "jpg",
    isUptoDate: true,
    modificationDate: "29.12.2021",
  },
  {
    id: 7,
    fileTitle: "B Blok Fotoğrafı",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: jpgLogo,
    extension: "jpg",
    isUptoDate: false,
    modificationDate: "20.12.2021",
  },
  {
    id: 8,
    fileTitle: "Proje Açıklaması",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: docxLogo,
    extension: "docx",
    isUptoDate: false,
    modificationDate: "20.12.2021",
  },
  {
    id: 9,
    fileTitle: "Yeşil Vadi Renderi",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: pngLogo,
    extension: "png",
    isUptoDate: true,
    modificationDate: "20.12.2021",
  },
  {
    id: 10,
    fileTitle: "Proje Sözleşmesi",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: docxLogo,
    extension: "docx",
    isUptoDate: true,
    modificationDate: "20.12.2021",
  },
  {
    id: 11,
    fileTitle: "Şantiye Fotoğrafı",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: jpgLogo,
    extension: "jpg",
    isUptoDate: false,
    modificationDate: "20.12.2021",
  },
  {
    id: 12,
    fileTitle: "Şantiye Raporu",
    includedProjects: ["Yeşil Vadi Konutları"],
    imageSrc: pdfLogo,
    extension: "pdf",
    isUptoDate: true,
    modificationDate: "20.12.2021",
  },
];

export default projectFiles;